version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

volumes:
  sites:
  logs:
